### ISSUE TITLE
Incorrect behavior of the ucf-to-xdc with additional dot in filename

### ISSUE THREAD

**Issue by Xtyll** [iDoka/eda-scripts#1]
If an input ucf file contain two dots into the name (one for extension and one as a part of the name) script generates error message:
sed: can't read ddr_pins.ucf: No such file or directory
And also generates an empty output file.

**Comment by iDoka** [comment]
@Andruwkoo , could you provide full path for reproduce that test case?

**Comment by Xtyll** [comment]
I have this path:
/home/username/projects/some_path_to_project/sdc/ddr_pins.xdc.ucf 
I used this command:
./ucf-to-xdc-noslew.sh ./ddr_pins.xdc.ucf
got this error message:
sed: can't read ddr_pins.ucf: No such file or directory
and empty file with this name:
ddr_pins.xdc

**Comment by iDoka** [comment]
Fixed. Please try it now.
