### ISSUE TITLE
Incorrect conversation of the ucf file with ucf-to-xdc script with mig7 output file

### ISSUE THREAD

**Issue by Xtyll** [iDoka/eda-scripts#2]
I generated DDR memory pinout with mig 7 series IP core. It saves ucf file. I'm tried to convert this file with your script, but I was unsuccessful. 
I attached input and output files.

[sdc.zip](https://github.com/iDoka/eda-scripts/files/4162102/sdc.zip)

**Comment by iDoka** [comment]
You case dont have SLEW codeword in ucf.
I make special version of converter for this case.
Please use script `ucf-to-xdc-noslew.sh`
